### ISSUE TITLE
When connecting nodejs and browser nodes they get disconnected.

### ISSUE THREAD

**Issue by fsvieira** [HighCWu/js-libp2p-webrtc-star-demo#1]
Hi, 

Great example, but I was unable to connect browser to nodejs. 

The problem is that when browser node and nodejs node connect, they immediately disconnect. 
But nodejs-to-nodejs and browser-to-browser works just fine. 

I also tried to run locally the signal server (https://github.com/libp2p/js-libp2p-webrtc-star/tree/master/packages/webrtc-star-signalling-server) but I got the same result. 

Can you help me please ?

**Comment by fsvieira** [comment]
Sorry, it was my mistake I got a old node version, now with version 16 works great. 
https://github.com/libp2p/js-libp2p-webrtc-star/issues/419

Thank you for doing this example.

**Comment by HighCWu** [comment]
I don't have time to verify the problem because I'm too busy. Very glad you solved the problem yourself and help anyone who may have the same problem by leaving a solution.
